name: Sync Test DB with Prod

on:
  issues:
    types: [closed]
  workflow_dispatch:

jobs:
  sync-db:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch Environment Variables & Sync DB
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          ENVIRONMENT_ID: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          set +x
      
          # Fetch Railway environment variables
          variables=$(curl -sS -X POST "https://backboard.railway.app/graphql/v2" \
            -H "Authorization: Bearer ${RAILWAY_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "query": "query(\$environmentId: String!, \$serviceId: String!, \$projectId: String!) { variables(environmentId: \$environmentId, serviceId: \$serviceId, projectId: \$projectId) }",
            "variables": {
              "environmentId": "${ENVIRONMENT_ID}",
              "serviceId": "${SERVICE_ID}",
              "projectId": "${PROJECT_ID}"
            }
          }
          EOF
          )
      
          eval $(echo "$variables" | jq -r '.data.variables | to_entries | .[] | @sh "export \(.key)=\(.value)"') > env_vars.env
          echo 'export DEVELOPMENT_DATABASE_URL="postgresql://postgres:postgres@localhost:5432/test_db"' >> env_vars.env

          # Dump the Railway database with --clean option
          pg_dump --clean "$DATABASE_PUBLIC_URL" > dump.sql

      - name: Upload DB Dump Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-db-dump
          path: dump.sql
          retention-days: 5

      - name: Upload Environment Variables Artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-vars
          path: env_vars.env
          retention-days: 5