name: Python Unit Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

env:
  PYTHONWARNDEFAULTENCODING: 'true'
  PY_COLORS: 1
  LOCAL_DB_URL: postgresql://postgres:postgres@localhost:5432/test_db

permissions:
  contents: read
  pull-requests: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    environment: Workflow
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          allow-prereleases: true

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install --with dev

      - name: Run Ruff Linting
        run: poetry run ruff check .
        
  test:
    name: "Build and Test"
    needs: lint
    runs-on: ubuntu-latest
    environment: workflow

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          allow-prereleases: true

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y
          
      - name: Install Dependencies
        run: |
          poetry install --with dev
          pip install psycopg2-binary python-dotenv
      
      - name: Sync schema and data from Railway
        env:
          RAILWAY_DATABASE_URL: ${{ secrets.RAILWAY_DATABASE_URL }}
        run: |
          # Check if secret is set (without revealing it)
          if [ -n "$RAILWAY_DATABASE_URL" ]; then
            echo "RAILWAY_DATABASE_URL is set"
          else
            echo "ERROR: RAILWAY_DATABASE_URL is not set"
            exit 1
          fi
            
          # Install dependencies
          pip install psycopg2-binary
            
          # Make script executable
          chmod +x .github/scripts/sync_railway_data.py
            
           # Run the sync script
          python .github/scripts/sync_railway_data.py
        
      - name: Run tests
        env:
          DATABASE_URL: ${{ env.LOCAL_DB_URL }}
        run: |
          poetry run pytest -v
